config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
root 'matomes#index'

resources :matomes, only:[:new, :create, :show]
resources :users, only: [:edit, :update]

end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/matome.rb
class Matome < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/models/subtitle.rb
class Subtitle < ActiveRecord::Base
end

app/models/text.rb
class Text < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates :name, presence: true, length: { maximum: 50}

  mount_uploader :avatar, AvatarUploader

  has_many :matomes




  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        name:     auth.info.nickname,
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end
end

app/controllers/matomes_controller.rb
class MatomesController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # def facebook
  #   callback_from :facebook
  # end

  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth'].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to :root and return
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :avatar, :profile, :homepage)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.haml
%footer
  .footerinner
    .footerlist
      %ul.footerul
        %li{class: "footerli"}
          会社概要
        %li{class: "footerli"}
          利用規約
        %li{class: "footerli"}
          プライバシー
        %li{class: "footerli"}
          ヘルプ
        %li{class: "footerli"}
          NEVERまとめ公式ブログ
      %p.footercopy
        %small
          %b LINE Cprporation

app/views/layouts/_header.html.haml
%header
  .headinner
    .headnav{role: "navigation"}
      %nav
        %ul.navul
          - if user_signed_in?
            %li.navli
              = link_to "ユーザーページ" do
                =image_tag "http://static.naver.jp/matome/img/common/no_img/user_20x20.png",style: "width: 20; height: 20;", class: "navlist1__img"
            %li.navli
              = link_to "まとめ作成", new_matome_path
            %li.navli
              = link_to "ログアウト", destroy_user_session_path, method: :delete
            %li.navli
              = link_to "設定", edit_user_path(current_user.id)
          -else
            %li.navli
              = link_to "まとめ作成", "投稿ページ"
            %li.navli
              = link_to "会員登録（無料）", new_user_registration_path
            %li.navli
              = link_to "ログイン", new_user_session_path
    .headtitle
      %h1.title
        = link_to root_path, title: "NAVER まとめ", class: "title__img" do
          =image_tag "neverまとめ.PNG"
    / %form#searchform
    /   %fieldset
    /     %legend.formhide
    /       検索
    /     .input
    /       .Minputinner
    /         %input.iinputtext
    /     %span.buttonwrap
    /       = submit_tag class: "buttonsearch", title: "検索"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Nevermatome
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    -flash.each do |key, value|
      = content_tag :div, value, class: "alert alert-#{key}"
    = yield
    = render "layouts/footer"

app/views/matomes/index.html.haml
.top
  .topinner.clearfix
    %p.topday
      %time{datetime: "今日"}
        %em{class: "mdTopDate01Today"}
          2016.11.3
        %span{class: "mdTopDate01week"}
          (Thu)
    / .MdSocialLink0
    %ul.linkul
      %li.linkli
        = link_to "https://www.facebook.com/navermatome" do
          %spsn.mdSocialLinks01url
            FACEBOOK
      %li.linkli
        = link_to "http://twitter.com/#!/matomenaver" do
          %span.mdSOCIAL01itot
            Twitter
      %li.linkli
        = link_to "http://matome.naver.jp/feed/hot" do
          %span.mdSOCIAL01i
            RSS
  .content
    .content_inner
      .content_left
        .content_category
        .content_topic
        .content_ranking
      .content_right
        .content_best

app/views/users/edit.html.haml
.edit
  = form_for @user do |f|
    .left
      .left_top
        .left_avatr
          = image_tag @user.avatar, width:"120", height: "120"
        %h3
          = @user.name
        .left_count
          %ul
            %li.left_count_matome1
              %span
                = @user.id
              %span
                まとめ作成
            %hr
            %li.left_count_matome2
              %span
                = @user.id
              %span
                月間ページビュー
      .left_bottom
    .right
      .config
        %h1 設定
        %p.lorn
          = link_to "NAVERアカウント情報の変更", edit_user_path(current_user)
        %hr
      .name
        %h3.aaaa 名前
        .name_form
          = f.text_field :name, size: "76"
      .image
        %h3.aaa プロフィール画像
        .avatr
          = image_tag "avatar.PNG"
        %p.ban
          画像一枚につき1024KBまでアップロ
          %br/
          JPG,JPEG,GIF,PNGのみ対応して
          %br/
          画像の著作権や肖像権を保護して
        %span.upload
          = f.file_field :avatar do
            = image_tag "アップロード.PNG"
      .profile
        %h3.self 自己紹介
        .selfprofile
          = f.text_area :profile, cols: "76", rows:"5"
      .url
        %h3 運営サイト
        .urlurl
          = f.text_field :homepage, size: "76"
      .button
        .submit
          = f.submit do
            = image_tag "保存.PNG"